// import { Inter } from 'next/font/google'
import { Karla, Josefin_Sans } from "next/font/google";
// import { Hedvig_Letters_Serif } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })
const karla = Karla({ subsets: ["latin"], display: "swap" });
const josefin = Josefin_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={karla.className}>{children}</body>
        </html>
    );
}
